### PR TITLE
Set transformation metadata for existing NGFF datasets

### LINKED ISSUE #106: modify the coordinateMetadata for old stacks
@ziw-liu @talonchandler @mattersoflight 
From our discussion during our lab meeting, there seems to be a need for us to be able to implement an API call that allows us to modify the coordinate metadata for the datastore.

Currently, to modify the coordinateMetadata I think one has to do the following for each `Position` (please correct me if I'm wrong):
```python
## Test writing to the metadata for existing arrays
dataset = open_ome_zarr(store_path, mode='r+')
print(dataset["0/0/0"].metadata.dict()['multiscales'][0]['coordinate_transformations'])
dataset["0/0/0"].metadata.dict()['multiscales'][0]['coordinate_transformations'][0]['translation']  = [0, 0, 0, 500, 500]
print(dataset["0/0/0"].metadata.dict()['multiscales'][0]['coordinate_transformations'])
dataset.close()
```

This is a lower-priority enhancement, but we will benefit from this to display the multiple positions without having to copy or duplicate data.

### PR DESCRIPTION
**Pull request by ziw-liu**
Resolves #106.

### CODE REVIEW

**Comment by ziw-liu** [comment]
```text
---------- coverage: platform darwin, python 3.9.16-final-0 ----------
Name                      Stmts   Miss  Cover
---------------------------------------------
iohub/__init__.py             4      0   100%
iohub/_version.py             2      0   100%
iohub/clearcontrol.py       179     13    93%
iohub/cli/__init__.py         0      0   100%
iohub/cli/cli.py             27      0   100%
iohub/convert.py            162     28    83%
iohub/display_utils.py       21      0   100%
iohub/multipagetiff.py      156     25    84%
iohub/ndtiff.py              69      2    97%
iohub/ngff.py               476     62    87%
iohub/ngff_meta.py          181     22    88%
iohub/reader.py             145     15    90%
iohub/reader_base.py         41      4    90%
iohub/singlepagetiff.py     161     19    88%
iohub/upti.py                86     69    20%
iohub/zarrfile.py           137     29    79%
---------------------------------------------
TOTAL                      1847    288    84%
```

**Comment by JoOkuma** [comment]
Hi @ziw-liu, 

My review is below:

 - I noticed you replaced `List` with `list`, I would do the same with `Tuple`.
 - What's the difference between `test_set_transform_image` and `test_set_transform_fov`? They look almost identical, and they have a lot of duplicated code, even though they're part of the tests, it can lead to increased maintenance in the future.
 - The tests in this PR show how it's extremely verbose to interact with metadata / transform in iohub. I think it would benefit from a more friendly API, for example, a `get_transform` method, what do you think @edyoshikun @ziw-liu ?

**Comment by ziw-liu** [comment]
> * The tests in this PR show how it's extremely verbose to interact with metadata / transform in iohub. I think it would benefit from a more friendly API, for example, a `get_transform` method, what do you think @edyoshikun @ziw-liu ?

True... Another possibility we explored during the recent meeting is that we add a transform attribute to `ImageArray`. So FOVs and each resolution level can have their own one-to-one mapped transform attribute.

**Comment by ziw-liu** [comment]
> * What's the difference between `test_set_transform_image` and `test_set_transform_fov`? They look almost identical, and they have a lot of duplicated code, even though they're part of the tests, it can lead to increased maintenance in the future.

One tests setting transformation for an image array (resolution level), the other tests setting transformation for a FOV (all the resolution levels). They are different fields in the metadata.

They do look confusingly similar, but also quite difficult to abstract. I can elevate 3-4 util functions with 1-2 lines each for maintainability's sake but not sure if it's worth it (it will only make the code longer) and whether it will just make it even more confusing.

**Pull request merged**
