### PR TITLE
Get NGFF channel index from name

### PR DESCRIPTION
**Pull request by ziw-liu**
Requested by #45.
Related to #58.

### CODE REVIEW

**Comment by ziw-liu** [comment]
```
---------- coverage: platform darwin, python 3.9.16-final-0 ----------
Name                      Stmts   Miss  Cover
---------------------------------------------
iohub/__init__.py             0      0   100%
iohub/_version.py             2      2     0%
iohub/cli/__init__.py         0      0   100%
iohub/cli/cli.py             24     24     0%
iohub/lf_utils.py            12      1    92%
iohub/multipagetiff.py      162     25    85%
iohub/ngff.py               408     76    81%
iohub/ngff_meta.py          181     20    89%
iohub/pycromanager.py        69      7    90%
iohub/reader.py             151     11    93%
iohub/reader_base.py         25      4    84%
iohub/singlepagetiff.py     155     20    87%
iohub/upti.py                87     70    20%
iohub/zarrfile.py           139     29    79%
---------------------------------------------
TOTAL                      1415    289    80%
```

**Comment by JoOkuma** [comment]
Hey @ziw-liu , I got this error running the changed example.

```python3
WARNING:root:Image has 2 channels, while the dataset  has 3.
Traceback (most recent call last):
  File "/home/jordao/Softwares/iohub/examples/single_fov_ome_zarr.py", line 30, in <module>
    dataset["img"] = tczyx
  File "/home/jordao/miniconda3/envs/iohub/lib/python3.10/site-packages/iohub/ngff.py", line 481, in __setitem__
    self.create_image(key, value)
  File "/home/jordao/miniconda3/envs/iohub/lib/python3.10/site-packages/iohub/ngff.py", line 531, in create_image
    self._group.array(
  File "/home/jordao/miniconda3/envs/iohub/lib/python3.10/site-packages/zarr/hierarchy.py", line 1187, in array
    return self._write_op(self._array_nosync, name, data, **kwargs)
  File "/home/jordao/miniconda3/envs/iohub/lib/python3.10/site-packages/zarr/hierarchy.py", line 895, in _write_op
    return f(*args, **kwargs)
  File "/home/jordao/miniconda3/envs/iohub/lib/python3.10/site-packages/zarr/hierarchy.py", line 1193, in _array_nosync
    return array(data, store=self._store, path=path, chunk_store=self._chunk_store,
  File "/home/jordao/miniconda3/envs/iohub/lib/python3.10/site-packages/zarr/creation.py", line 394, in array
    z = create(**kwargs)
  File "/home/jordao/miniconda3/envs/iohub/lib/python3.10/site-packages/zarr/creation.py", line 178, in create
    init_array(store, shape=shape, chunks=chunks, dtype=dtype, compressor=compressor,
  File "/home/jordao/miniconda3/envs/iohub/lib/python3.10/site-packages/zarr/storage.py", line 437, in init_array
    _init_array_metadata(store, shape=shape, chunks=chunks, dtype=dtype,
  File "/home/jordao/miniconda3/envs/iohub/lib/python3.10/site-packages/zarr/storage.py", line 498, in _init_array_metadata
    raise ContainsArrayError(path)
zarr.errors.ContainsArrayError: path 'img' contains an array
```

**Comment by edyoshikun** [comment]
@JoOkuma  That's because you already created a zarr store with that position. You can do `dataset.print_tree()` to check the store tree.

**Comment by JoOkuma** [comment]
@edyoshikun got it, thanks

**Review by JoOkuma — APPROVED** [review]
LGTM!

**Comment by edyoshikun** [comment]
This worked well on my side. Thanks @ziw-liu

**Pull request merged**
