### PR TITLE
Pydata theme for documentation

### PR DESCRIPTION
**Pull request by ziw-liu**
See discussion at #28. We thought TOC trees doesn't work in this theme but it just requires a different syntax.

Also includes minor fixes/rewording of documentation content.

### CODE REVIEW

**Review by AhmetCanSolak — APPROVED** [review]
looks good to me, if this theme is agreed on. No strong preference on the theme.

**Review by keithchev — APPROVED** [review]

**Comment by mattersoflight** [comment]
@ziw-liu I ran into error when installing the dependencies with 
`pip install "<path_to_iohub>[doc]` 

<details><summary>Details</summary>
<p>

```
Processing /Users/shalin.mehta/Documents/code/iohub
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [43 lines of output]

....
....
 File "/private/var/folders/2w/3lz_vt297916ljyjzhtwvsf00000gp/T/pip-build-env-_levik4c/overlay/lib/python3.9/site-packages/setuptools_scm/version.py", line 271, in _bump_dev
          raise ValueError(
      ValueError: choosing custom numbers for the `.devX` distance is not supported.
       The 0.1.0.dev1 can't be bumped
      Please drop the tag or create a new supported one ending in .dev0
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.

```

</p>
</details>

**Comment by talonchandler** [comment]
@mattersoflight try installing with #125.

**Review by mattersoflight — APPROVED** [review]
After merging #125, LGTM!

**Comment by ziw-liu** [comment]
Made some minor edits. Merging.

**Pull request merged**
