### PR TITLE
Methods for modifying channels in NGFF positions

### LINKED ISSUE #56: Method to delete or rename channel in NGFF datasets
Branching off of #45:
#31 has a convenience method for appending new channels to a NGFF position node, but there is no easy way to delete or rename an existing channel so that arrays and metadata all get updated properly.

### PR DESCRIPTION
**Pull request by ziw-liu**
Resolves #56.

### CODE REVIEW

**Comment by ziw-liu** [comment]
Channel deletion has not been implemented due performance and data safety concerns.

**Comment by ziw-liu** [comment]
```
---------- coverage: platform darwin, python 3.9.16-final-0 ----------
Name                      Stmts   Miss  Cover
---------------------------------------------
iohub/__init__.py             0      0   100%
iohub/_version.py             2      2     0%
iohub/cli/__init__.py         0      0   100%
iohub/cli/cli.py             24     24     0%
iohub/lf_utils.py            12      1    92%
iohub/multipagetiff.py      162     25    85%
iohub/ngff.py               400     78    80%
iohub/ngff_meta.py          181     20    89%
iohub/pycromanager.py        69     11    84%
iohub/reader.py             148      8    95%
iohub/reader_base.py         25      4    84%
iohub/singlepagetiff.py     155     20    87%
iohub/upti.py                87     70    20%
iohub/zarrfile.py           136     27    80%
---------------------------------------------
TOTAL                      1401    290    79%
```

**Comment by JoOkuma** [comment]
Hi @ziw-liu , I'll give it a try reviewing this PR.
It's my first time reviewing a larger PR in iohub, so there are few things I need to get familiar with.

**Comment by JoOkuma** [comment]
I got this error when running the updated example:

```python3
<iohub.ngff.ImageArray '/img' (5, 2, 3, 32, 32) uint16 read-only>
[[[[[61254   624 17325 ... 60666 16213 10256]
    [51498 24668 28521 ...  9281 38275 60791]
...
    [ 6127  7014 29873 ...  3102 60312 32309]]]]]
Writing was rejected: object is read-only
(5, 2, 3, 32, 32)
(6, 2, 3, 32, 32)
/
 └── img (6, 2, 3, 32, 32) uint16
['DAPI', 'GFP', 'New']
/
 └── img (6, 3, 3, 32, 32) uint16
['DAPI', 'GFP', 'Renamed']
Traceback (most recent call last):
  File "/home/jordao/Softwares/iohub/examples/single_fov_ome_zarr.py", line 81, in <module>
    dataset["img"][:, 2] = new_tzyx
  File "/home/jordao/miniconda3/envs/iohub/lib/python3.10/site-packages/zarr/core.py", line 1391, in __setitem__
    self.set_basic_selection(pure_selection, value, fields=fields)
  File "/home/jordao/miniconda3/envs/iohub/lib/python3.10/site-packages/zarr/core.py", line 1486, in set_basic_selection
    return self._set_basic_selection_nd(selection, value, fields=fields)
  File "/home/jordao/miniconda3/envs/iohub/lib/python3.10/site-packages/zarr/core.py", line 1790, in _set_basic_selection_nd
    self._set_selection(indexer, value, fields=fields)
  File "/home/jordao/miniconda3/envs/iohub/lib/python3.10/site-packages/zarr/core.py", line 1818, in _set_selection
    check_array_shape('value', value, sel_shape)
  File "/home/jordao/miniconda3/envs/iohub/lib/python3.10/site-packages/zarr/util.py", line 551, in check_array_shape
    raise ValueError('parameter {!r}: expected array with shape {!r}, got {!r}'
ValueError: parameter 'value': expected array with shape (6, 3, 32, 32), got (5, 3, 32, 32)
```

**Comment by JoOkuma** [comment]
LGTM, @ziw-liu, thanks for taking the time to pair review with me.

**Review by JoOkuma — APPROVED** [review]

**Pull request merged**
