### PR TITLE
Initialize Zarr arrays in TIFF readers as zero-filled

### LINKED ISSUE #82: `get_zarr` returns incorrect data from 3D + 2D MM datasets
Here's a minimal demonstration of the issue
```
>>> from iohub.reader import imread
>>> reader = imread('/hpc/projects/compmicro/rawdata/other/NIC QLIPP/2022_12_01 PtK cells/FOV1_1')

>>> reader.get_zarr(0)[0,-1,:,500,500] # get the Z profile over the last channel
array([28992, 48564, 22054,     0,     0,     0,     0,     0, 11040,
       19283, 20553,  8202,  8224, 21536, 30821, 10356, 11824, 11317,
       12320,  8236,   631, 10535,  8202,  8224, 15904, 15934, 28704,
       29804, 29486, 28520, 10359,  8233,  8992, 25632, 25455, 25972,
       29811,  8250, 21291, 18763,   224], dtype=uint16)

>>> reader.get_zarr(0)[0,-1,:,500,500] # repeated call gives a different result!
array([21184, 48542, 22054,     0,     0,     0,     0,     0,  2570,
       25939,  8293, 27713, 28531, 11530, 11565, 11565, 11565,  2605,
       27750, 24943,   631, 28528, 25975,  8306,  8250, 28528, 25975,
        8306, 30054, 25454, 26996, 28271, 29728, 24936,  8308, 29296,
       28015, 29807, 29541, 26912,   224], dtype=uint16)

>>> reader.get_array(0)[0,-1,:,500,500] # get_array gives the expected result
array([  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0, 631,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0], dtype=uint16)
```

**Notes**
- This dataset is a 3D + 2D dataset from MM...only the 2D channel fails on repeated `get_zarr` calls
- To see the correct result, use `get_array`, open the dataset in MM, or open with `napari`'s `builtin` reader 
- I tested this issue on the `converter` branch with the new `imread` function, and I also confirmed that it was inherited from the `WaveorderReader`. 

**Symptoms:**
- `recorder view` uses `get_zarr` (currently the `WaveorderReader` version...with the same behaviour) and behaves erratically when you scroll through Z in napari
- Tagging @ieivanov because this issue affects the spindle data from the NIC. This issue is not blocking (scripts can use `get_array` for now), but it is an strong inconvenience since it blocks many of the `napari` viewing conveniences that we're used to.

### PR DESCRIPTION
**Pull request by ziw-liu**
Fixes #82 and https://github.com/mehta-lab/recOrder/issues/327#issuecomment-1479897823.

The converter will now log a warning and fill with zeros instead of throwing an error if certain images are not present in the OME-TIFF series.

Edit: Test that repeated reads return the same values.

```python
In [1]: from iohub.reader import imread

In [2]: reader = imread('/hpc/projects/compmicro/rawdata/other/NIC QLIPP/2022_12_01 PtK cells/FOV1_1')

In [4]: reader.get_zarr(0)[0,-1,:,500,500]
Out[4]:
array([  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0, 631,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0], dtype=uint16)

In [5]: reader.get_zarr(0)[0,-1,:,500,500]
Out[5]:
array([  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0, 631,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0], dtype=uint16)

In [6]: reader.get_zarr(0)[0,-1,:,500,500]
Out[6]:
array([  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0, 631,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0], dtype=uint16)
```

### CODE REVIEW

**Review by talonchandler — APPROVED** [review]
Double approval from me!

This also fixes `recOrder` #327---an issue with converting 3D + 2D micromanager datasets. I was expecting some grimy work with index maps to fix that, but this solution is much better. Thanks again @ziw-liu.

**Comment by mattersoflight** [comment]
Nice solution @ziw-liu!

**Comment by mattersoflight** [comment]
@ieivanov can you review this too?

**Comment by ieivanov** [comment]
I haven't run the code, but everything seems reasonable to me. Talon has run the code, and as I understand it, it works well. Approving, we can merge.

**Review by ieivanov — APPROVED** [review]

**Pull request merged**
